/**
 *
 *  Detail.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Detail.h"
#include "Picture.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::sqlite3;

const std::string Detail::Cols::_id = "id";
const std::string Detail::Cols::_train_num = "train_num";
const std::string Detail::Cols::_dead_weight = "dead_weight";
const std::string Detail::Cols::_rough_weight = "rough_weight";
const std::string Detail::Cols::_volume = "volume";
const std::string Detail::Cols::_length = "length";
const std::string Detail::Cols::_train_num_url = "train_num_url";
const std::string Detail::Cols::_dead_weight_url = "dead_weight_url";
const std::string Detail::Cols::_rough_weight_url = "rough_weight_url";
const std::string Detail::Cols::_volume_url = "volume_url";
const std::string Detail::Cols::_length_url = "length_url";
const std::string Detail::Cols::_picture_id = "picture_id";
const std::string Detail::primaryKeyName = "id";
const bool Detail::hasPrimaryKey = true;
const std::string Detail::tableName = "detail";

const std::vector<typename Detail::MetaData> Detail::metaData_={
{"id","uint64_t","integer",8,1,1,1},
{"train_num","std::string","text",0,0,0,0},
{"dead_weight","double","real",8,0,0,0},
{"rough_weight","double","real",8,0,0,0},
{"volume","double","real",8,0,0,0},
{"length","double","real",8,0,0,0},
{"train_num_url","uint64_t","integer",8,0,0,0},
{"dead_weight_url","uint64_t","integer",8,0,0,0},
{"rough_weight_url","uint64_t","integer",8,0,0,0},
{"volume_url","uint64_t","integer",8,0,0,0},
{"length_url","uint64_t","integer",8,0,0,0},
{"picture_id","uint64_t","integer",8,0,0,0}
};
const std::string &Detail::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Detail::Detail(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<uint64_t>(r["id"].as<uint64_t>());
        }
        if(!r["train_num"].isNull())
        {
            trainNum_=std::make_shared<std::string>(r["train_num"].as<std::string>());
        }
        if(!r["dead_weight"].isNull())
        {
            deadWeight_=std::make_shared<double>(r["dead_weight"].as<double>());
        }
        if(!r["rough_weight"].isNull())
        {
            roughWeight_=std::make_shared<double>(r["rough_weight"].as<double>());
        }
        if(!r["volume"].isNull())
        {
            volume_=std::make_shared<double>(r["volume"].as<double>());
        }
        if(!r["length"].isNull())
        {
            length_=std::make_shared<double>(r["length"].as<double>());
        }
        if(!r["train_num_url"].isNull())
        {
            trainNumUrl_=std::make_shared<uint64_t>(r["train_num_url"].as<uint64_t>());
        }
        if(!r["dead_weight_url"].isNull())
        {
            deadWeightUrl_=std::make_shared<uint64_t>(r["dead_weight_url"].as<uint64_t>());
        }
        if(!r["rough_weight_url"].isNull())
        {
            roughWeightUrl_=std::make_shared<uint64_t>(r["rough_weight_url"].as<uint64_t>());
        }
        if(!r["volume_url"].isNull())
        {
            volumeUrl_=std::make_shared<uint64_t>(r["volume_url"].as<uint64_t>());
        }
        if(!r["length_url"].isNull())
        {
            lengthUrl_=std::make_shared<uint64_t>(r["length_url"].as<uint64_t>());
        }
        if(!r["picture_id"].isNull())
        {
            pictureId_=std::make_shared<uint64_t>(r["picture_id"].as<uint64_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 12 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            trainNum_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            deadWeight_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            roughWeight_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            volume_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            length_=std::make_shared<double>(r[index].as<double>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            trainNumUrl_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            deadWeightUrl_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            roughWeightUrl_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            volumeUrl_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            lengthUrl_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            pictureId_=std::make_shared<uint64_t>(r[index].as<uint64_t>());
        }
    }

}

Detail::Detail(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trainNum_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            deadWeight_=std::make_shared<double>(pJson[pMasqueradingVector[2]].asDouble());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            roughWeight_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            volume_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            length_=std::make_shared<double>(pJson[pMasqueradingVector[5]].asDouble());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            trainNumUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[6]].asUInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            deadWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[7]].asUInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            roughWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[8]].asUInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            volumeUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[9]].asUInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            lengthUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[10]].asUInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            pictureId_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[11]].asUInt64());
        }
    }
}

Detail::Detail(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("train_num"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["train_num"].isNull())
        {
            trainNum_=std::make_shared<std::string>(pJson["train_num"].asString());
        }
    }
    if(pJson.isMember("dead_weight"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["dead_weight"].isNull())
        {
            deadWeight_=std::make_shared<double>(pJson["dead_weight"].asDouble());
        }
    }
    if(pJson.isMember("rough_weight"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["rough_weight"].isNull())
        {
            roughWeight_=std::make_shared<double>(pJson["rough_weight"].asDouble());
        }
    }
    if(pJson.isMember("volume"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["volume"].isNull())
        {
            volume_=std::make_shared<double>(pJson["volume"].asDouble());
        }
    }
    if(pJson.isMember("length"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["length"].isNull())
        {
            length_=std::make_shared<double>(pJson["length"].asDouble());
        }
    }
    if(pJson.isMember("train_num_url"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["train_num_url"].isNull())
        {
            trainNumUrl_=std::make_shared<uint64_t>((uint64_t)pJson["train_num_url"].asUInt64());
        }
    }
    if(pJson.isMember("dead_weight_url"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["dead_weight_url"].isNull())
        {
            deadWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson["dead_weight_url"].asUInt64());
        }
    }
    if(pJson.isMember("rough_weight_url"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["rough_weight_url"].isNull())
        {
            roughWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson["rough_weight_url"].asUInt64());
        }
    }
    if(pJson.isMember("volume_url"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["volume_url"].isNull())
        {
            volumeUrl_=std::make_shared<uint64_t>((uint64_t)pJson["volume_url"].asUInt64());
        }
    }
    if(pJson.isMember("length_url"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["length_url"].isNull())
        {
            lengthUrl_=std::make_shared<uint64_t>((uint64_t)pJson["length_url"].asUInt64());
        }
    }
    if(pJson.isMember("picture_id"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["picture_id"].isNull())
        {
            pictureId_=std::make_shared<uint64_t>((uint64_t)pJson["picture_id"].asUInt64());
        }
    }
}

void Detail::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 12)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[0]].asUInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            trainNum_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            deadWeight_=std::make_shared<double>(pJson[pMasqueradingVector[2]].asDouble());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            roughWeight_=std::make_shared<double>(pJson[pMasqueradingVector[3]].asDouble());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            volume_=std::make_shared<double>(pJson[pMasqueradingVector[4]].asDouble());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            length_=std::make_shared<double>(pJson[pMasqueradingVector[5]].asDouble());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            trainNumUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[6]].asUInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            deadWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[7]].asUInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            roughWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[8]].asUInt64());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            volumeUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[9]].asUInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            lengthUrl_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[10]].asUInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            pictureId_=std::make_shared<uint64_t>((uint64_t)pJson[pMasqueradingVector[11]].asUInt64());
        }
    }
}

void Detail::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<uint64_t>((uint64_t)pJson["id"].asUInt64());
        }
    }
    if(pJson.isMember("train_num"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["train_num"].isNull())
        {
            trainNum_=std::make_shared<std::string>(pJson["train_num"].asString());
        }
    }
    if(pJson.isMember("dead_weight"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["dead_weight"].isNull())
        {
            deadWeight_=std::make_shared<double>(pJson["dead_weight"].asDouble());
        }
    }
    if(pJson.isMember("rough_weight"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["rough_weight"].isNull())
        {
            roughWeight_=std::make_shared<double>(pJson["rough_weight"].asDouble());
        }
    }
    if(pJson.isMember("volume"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["volume"].isNull())
        {
            volume_=std::make_shared<double>(pJson["volume"].asDouble());
        }
    }
    if(pJson.isMember("length"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["length"].isNull())
        {
            length_=std::make_shared<double>(pJson["length"].asDouble());
        }
    }
    if(pJson.isMember("train_num_url"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["train_num_url"].isNull())
        {
            trainNumUrl_=std::make_shared<uint64_t>((uint64_t)pJson["train_num_url"].asUInt64());
        }
    }
    if(pJson.isMember("dead_weight_url"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["dead_weight_url"].isNull())
        {
            deadWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson["dead_weight_url"].asUInt64());
        }
    }
    if(pJson.isMember("rough_weight_url"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["rough_weight_url"].isNull())
        {
            roughWeightUrl_=std::make_shared<uint64_t>((uint64_t)pJson["rough_weight_url"].asUInt64());
        }
    }
    if(pJson.isMember("volume_url"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["volume_url"].isNull())
        {
            volumeUrl_=std::make_shared<uint64_t>((uint64_t)pJson["volume_url"].asUInt64());
        }
    }
    if(pJson.isMember("length_url"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["length_url"].isNull())
        {
            lengthUrl_=std::make_shared<uint64_t>((uint64_t)pJson["length_url"].asUInt64());
        }
    }
    if(pJson.isMember("picture_id"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["picture_id"].isNull())
        {
            pictureId_=std::make_shared<uint64_t>((uint64_t)pJson["picture_id"].asUInt64());
        }
    }
}

const uint64_t &Detail::getValueOfId() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Detail::getId() const noexcept
{
    return id_;
}
void Detail::setId(const uint64_t &pId) noexcept
{
    id_ = std::make_shared<uint64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename Detail::PrimaryKeyType & Detail::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const std::string &Detail::getValueOfTrainNum() const noexcept
{
    const static std::string defaultValue = std::string();
    if(trainNum_)
        return *trainNum_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Detail::getTrainNum() const noexcept
{
    return trainNum_;
}
void Detail::setTrainNum(const std::string &pTrainNum) noexcept
{
    trainNum_ = std::make_shared<std::string>(pTrainNum);
    dirtyFlag_[1] = true;
}
void Detail::setTrainNum(std::string &&pTrainNum) noexcept
{
    trainNum_ = std::make_shared<std::string>(std::move(pTrainNum));
    dirtyFlag_[1] = true;
}
void Detail::setTrainNumToNull() noexcept
{
    trainNum_.reset();
    dirtyFlag_[1] = true;
}

const double &Detail::getValueOfDeadWeight() const noexcept
{
    const static double defaultValue = double();
    if(deadWeight_)
        return *deadWeight_;
    return defaultValue;
}
const std::shared_ptr<double> &Detail::getDeadWeight() const noexcept
{
    return deadWeight_;
}
void Detail::setDeadWeight(const double &pDeadWeight) noexcept
{
    deadWeight_ = std::make_shared<double>(pDeadWeight);
    dirtyFlag_[2] = true;
}
void Detail::setDeadWeightToNull() noexcept
{
    deadWeight_.reset();
    dirtyFlag_[2] = true;
}

const double &Detail::getValueOfRoughWeight() const noexcept
{
    const static double defaultValue = double();
    if(roughWeight_)
        return *roughWeight_;
    return defaultValue;
}
const std::shared_ptr<double> &Detail::getRoughWeight() const noexcept
{
    return roughWeight_;
}
void Detail::setRoughWeight(const double &pRoughWeight) noexcept
{
    roughWeight_ = std::make_shared<double>(pRoughWeight);
    dirtyFlag_[3] = true;
}
void Detail::setRoughWeightToNull() noexcept
{
    roughWeight_.reset();
    dirtyFlag_[3] = true;
}

const double &Detail::getValueOfVolume() const noexcept
{
    const static double defaultValue = double();
    if(volume_)
        return *volume_;
    return defaultValue;
}
const std::shared_ptr<double> &Detail::getVolume() const noexcept
{
    return volume_;
}
void Detail::setVolume(const double &pVolume) noexcept
{
    volume_ = std::make_shared<double>(pVolume);
    dirtyFlag_[4] = true;
}
void Detail::setVolumeToNull() noexcept
{
    volume_.reset();
    dirtyFlag_[4] = true;
}

const double &Detail::getValueOfLength() const noexcept
{
    const static double defaultValue = double();
    if(length_)
        return *length_;
    return defaultValue;
}
const std::shared_ptr<double> &Detail::getLength() const noexcept
{
    return length_;
}
void Detail::setLength(const double &pLength) noexcept
{
    length_ = std::make_shared<double>(pLength);
    dirtyFlag_[5] = true;
}
void Detail::setLengthToNull() noexcept
{
    length_.reset();
    dirtyFlag_[5] = true;
}

const uint64_t &Detail::getValueOfTrainNumUrl() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(trainNumUrl_)
        return *trainNumUrl_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Detail::getTrainNumUrl() const noexcept
{
    return trainNumUrl_;
}
void Detail::setTrainNumUrl(const uint64_t &pTrainNumUrl) noexcept
{
    trainNumUrl_ = std::make_shared<uint64_t>(pTrainNumUrl);
    dirtyFlag_[6] = true;
}
void Detail::setTrainNumUrlToNull() noexcept
{
    trainNumUrl_.reset();
    dirtyFlag_[6] = true;
}

const uint64_t &Detail::getValueOfDeadWeightUrl() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(deadWeightUrl_)
        return *deadWeightUrl_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Detail::getDeadWeightUrl() const noexcept
{
    return deadWeightUrl_;
}
void Detail::setDeadWeightUrl(const uint64_t &pDeadWeightUrl) noexcept
{
    deadWeightUrl_ = std::make_shared<uint64_t>(pDeadWeightUrl);
    dirtyFlag_[7] = true;
}
void Detail::setDeadWeightUrlToNull() noexcept
{
    deadWeightUrl_.reset();
    dirtyFlag_[7] = true;
}

const uint64_t &Detail::getValueOfRoughWeightUrl() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(roughWeightUrl_)
        return *roughWeightUrl_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Detail::getRoughWeightUrl() const noexcept
{
    return roughWeightUrl_;
}
void Detail::setRoughWeightUrl(const uint64_t &pRoughWeightUrl) noexcept
{
    roughWeightUrl_ = std::make_shared<uint64_t>(pRoughWeightUrl);
    dirtyFlag_[8] = true;
}
void Detail::setRoughWeightUrlToNull() noexcept
{
    roughWeightUrl_.reset();
    dirtyFlag_[8] = true;
}

const uint64_t &Detail::getValueOfVolumeUrl() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(volumeUrl_)
        return *volumeUrl_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Detail::getVolumeUrl() const noexcept
{
    return volumeUrl_;
}
void Detail::setVolumeUrl(const uint64_t &pVolumeUrl) noexcept
{
    volumeUrl_ = std::make_shared<uint64_t>(pVolumeUrl);
    dirtyFlag_[9] = true;
}
void Detail::setVolumeUrlToNull() noexcept
{
    volumeUrl_.reset();
    dirtyFlag_[9] = true;
}

const uint64_t &Detail::getValueOfLengthUrl() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(lengthUrl_)
        return *lengthUrl_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Detail::getLengthUrl() const noexcept
{
    return lengthUrl_;
}
void Detail::setLengthUrl(const uint64_t &pLengthUrl) noexcept
{
    lengthUrl_ = std::make_shared<uint64_t>(pLengthUrl);
    dirtyFlag_[10] = true;
}
void Detail::setLengthUrlToNull() noexcept
{
    lengthUrl_.reset();
    dirtyFlag_[10] = true;
}

const uint64_t &Detail::getValueOfPictureId() const noexcept
{
    const static uint64_t defaultValue = uint64_t();
    if(pictureId_)
        return *pictureId_;
    return defaultValue;
}
const std::shared_ptr<uint64_t> &Detail::getPictureId() const noexcept
{
    return pictureId_;
}
void Detail::setPictureId(const uint64_t &pPictureId) noexcept
{
    pictureId_ = std::make_shared<uint64_t>(pPictureId);
    dirtyFlag_[11] = true;
}
void Detail::setPictureIdToNull() noexcept
{
    pictureId_.reset();
    dirtyFlag_[11] = true;
}

void Detail::updateId(const uint64_t id)
{
    id_ = std::make_shared<uint64_t>(id);
}

const std::vector<std::string> &Detail::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "train_num",
        "dead_weight",
        "rough_weight",
        "volume",
        "length",
        "train_num_url",
        "dead_weight_url",
        "rough_weight_url",
        "volume_url",
        "length_url",
        "picture_id"
    };
    return inCols;
}

void Detail::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrainNum())
        {
            binder << getValueOfTrainNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDeadWeight())
        {
            binder << getValueOfDeadWeight();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRoughWeight())
        {
            binder << getValueOfRoughWeight();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getVolume())
        {
            binder << getValueOfVolume();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLength())
        {
            binder << getValueOfLength();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTrainNumUrl())
        {
            binder << getValueOfTrainNumUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDeadWeightUrl())
        {
            binder << getValueOfDeadWeightUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRoughWeightUrl())
        {
            binder << getValueOfRoughWeightUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getVolumeUrl())
        {
            binder << getValueOfVolumeUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLengthUrl())
        {
            binder << getValueOfLengthUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getPictureId())
        {
            binder << getValueOfPictureId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Detail::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    return ret;
}

void Detail::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTrainNum())
        {
            binder << getValueOfTrainNum();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getDeadWeight())
        {
            binder << getValueOfDeadWeight();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRoughWeight())
        {
            binder << getValueOfRoughWeight();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getVolume())
        {
            binder << getValueOfVolume();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getLength())
        {
            binder << getValueOfLength();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTrainNumUrl())
        {
            binder << getValueOfTrainNumUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDeadWeightUrl())
        {
            binder << getValueOfDeadWeightUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRoughWeightUrl())
        {
            binder << getValueOfRoughWeightUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getVolumeUrl())
        {
            binder << getValueOfVolumeUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getLengthUrl())
        {
            binder << getValueOfLengthUrl();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getPictureId())
        {
            binder << getValueOfPictureId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Detail::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::UInt64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrainNum())
    {
        ret["train_num"]=getValueOfTrainNum();
    }
    else
    {
        ret["train_num"]=Json::Value();
    }
    if(getDeadWeight())
    {
        ret["dead_weight"]=getValueOfDeadWeight();
    }
    else
    {
        ret["dead_weight"]=Json::Value();
    }
    if(getRoughWeight())
    {
        ret["rough_weight"]=getValueOfRoughWeight();
    }
    else
    {
        ret["rough_weight"]=Json::Value();
    }
    if(getVolume())
    {
        ret["volume"]=getValueOfVolume();
    }
    else
    {
        ret["volume"]=Json::Value();
    }
    if(getLength())
    {
        ret["length"]=getValueOfLength();
    }
    else
    {
        ret["length"]=Json::Value();
    }
    if(getTrainNumUrl())
    {
        ret["train_num_url"]=(Json::UInt64)getValueOfTrainNumUrl();
    }
    else
    {
        ret["train_num_url"]=Json::Value();
    }
    if(getDeadWeightUrl())
    {
        ret["dead_weight_url"]=(Json::UInt64)getValueOfDeadWeightUrl();
    }
    else
    {
        ret["dead_weight_url"]=Json::Value();
    }
    if(getRoughWeightUrl())
    {
        ret["rough_weight_url"]=(Json::UInt64)getValueOfRoughWeightUrl();
    }
    else
    {
        ret["rough_weight_url"]=Json::Value();
    }
    if(getVolumeUrl())
    {
        ret["volume_url"]=(Json::UInt64)getValueOfVolumeUrl();
    }
    else
    {
        ret["volume_url"]=Json::Value();
    }
    if(getLengthUrl())
    {
        ret["length_url"]=(Json::UInt64)getValueOfLengthUrl();
    }
    else
    {
        ret["length_url"]=Json::Value();
    }
    if(getPictureId())
    {
        ret["picture_id"]=(Json::UInt64)getValueOfPictureId();
    }
    else
    {
        ret["picture_id"]=Json::Value();
    }
    return ret;
}

Json::Value Detail::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 12)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::UInt64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTrainNum())
            {
                ret[pMasqueradingVector[1]]=getValueOfTrainNum();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getDeadWeight())
            {
                ret[pMasqueradingVector[2]]=getValueOfDeadWeight();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRoughWeight())
            {
                ret[pMasqueradingVector[3]]=getValueOfRoughWeight();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getVolume())
            {
                ret[pMasqueradingVector[4]]=getValueOfVolume();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getLength())
            {
                ret[pMasqueradingVector[5]]=getValueOfLength();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getTrainNumUrl())
            {
                ret[pMasqueradingVector[6]]=(Json::UInt64)getValueOfTrainNumUrl();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDeadWeightUrl())
            {
                ret[pMasqueradingVector[7]]=(Json::UInt64)getValueOfDeadWeightUrl();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getRoughWeightUrl())
            {
                ret[pMasqueradingVector[8]]=(Json::UInt64)getValueOfRoughWeightUrl();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getVolumeUrl())
            {
                ret[pMasqueradingVector[9]]=(Json::UInt64)getValueOfVolumeUrl();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getLengthUrl())
            {
                ret[pMasqueradingVector[10]]=(Json::UInt64)getValueOfLengthUrl();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getPictureId())
            {
                ret[pMasqueradingVector[11]]=(Json::UInt64)getValueOfPictureId();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::UInt64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTrainNum())
    {
        ret["train_num"]=getValueOfTrainNum();
    }
    else
    {
        ret["train_num"]=Json::Value();
    }
    if(getDeadWeight())
    {
        ret["dead_weight"]=getValueOfDeadWeight();
    }
    else
    {
        ret["dead_weight"]=Json::Value();
    }
    if(getRoughWeight())
    {
        ret["rough_weight"]=getValueOfRoughWeight();
    }
    else
    {
        ret["rough_weight"]=Json::Value();
    }
    if(getVolume())
    {
        ret["volume"]=getValueOfVolume();
    }
    else
    {
        ret["volume"]=Json::Value();
    }
    if(getLength())
    {
        ret["length"]=getValueOfLength();
    }
    else
    {
        ret["length"]=Json::Value();
    }
    if(getTrainNumUrl())
    {
        ret["train_num_url"]=(Json::UInt64)getValueOfTrainNumUrl();
    }
    else
    {
        ret["train_num_url"]=Json::Value();
    }
    if(getDeadWeightUrl())
    {
        ret["dead_weight_url"]=(Json::UInt64)getValueOfDeadWeightUrl();
    }
    else
    {
        ret["dead_weight_url"]=Json::Value();
    }
    if(getRoughWeightUrl())
    {
        ret["rough_weight_url"]=(Json::UInt64)getValueOfRoughWeightUrl();
    }
    else
    {
        ret["rough_weight_url"]=Json::Value();
    }
    if(getVolumeUrl())
    {
        ret["volume_url"]=(Json::UInt64)getValueOfVolumeUrl();
    }
    else
    {
        ret["volume_url"]=Json::Value();
    }
    if(getLengthUrl())
    {
        ret["length_url"]=(Json::UInt64)getValueOfLengthUrl();
    }
    else
    {
        ret["length_url"]=Json::Value();
    }
    if(getPictureId())
    {
        ret["picture_id"]=(Json::UInt64)getValueOfPictureId();
    }
    else
    {
        ret["picture_id"]=Json::Value();
    }
    return ret;
}

bool Detail::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("train_num"))
    {
        if(!validJsonOfField(1, "train_num", pJson["train_num"], err, true))
            return false;
    }
    if(pJson.isMember("dead_weight"))
    {
        if(!validJsonOfField(2, "dead_weight", pJson["dead_weight"], err, true))
            return false;
    }
    if(pJson.isMember("rough_weight"))
    {
        if(!validJsonOfField(3, "rough_weight", pJson["rough_weight"], err, true))
            return false;
    }
    if(pJson.isMember("volume"))
    {
        if(!validJsonOfField(4, "volume", pJson["volume"], err, true))
            return false;
    }
    if(pJson.isMember("length"))
    {
        if(!validJsonOfField(5, "length", pJson["length"], err, true))
            return false;
    }
    if(pJson.isMember("train_num_url"))
    {
        if(!validJsonOfField(6, "train_num_url", pJson["train_num_url"], err, true))
            return false;
    }
    if(pJson.isMember("dead_weight_url"))
    {
        if(!validJsonOfField(7, "dead_weight_url", pJson["dead_weight_url"], err, true))
            return false;
    }
    if(pJson.isMember("rough_weight_url"))
    {
        if(!validJsonOfField(8, "rough_weight_url", pJson["rough_weight_url"], err, true))
            return false;
    }
    if(pJson.isMember("volume_url"))
    {
        if(!validJsonOfField(9, "volume_url", pJson["volume_url"], err, true))
            return false;
    }
    if(pJson.isMember("length_url"))
    {
        if(!validJsonOfField(10, "length_url", pJson["length_url"], err, true))
            return false;
    }
    if(pJson.isMember("picture_id"))
    {
        if(!validJsonOfField(11, "picture_id", pJson["picture_id"], err, true))
            return false;
    }
    return true;
}
bool Detail::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Detail::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("train_num"))
    {
        if(!validJsonOfField(1, "train_num", pJson["train_num"], err, false))
            return false;
    }
    if(pJson.isMember("dead_weight"))
    {
        if(!validJsonOfField(2, "dead_weight", pJson["dead_weight"], err, false))
            return false;
    }
    if(pJson.isMember("rough_weight"))
    {
        if(!validJsonOfField(3, "rough_weight", pJson["rough_weight"], err, false))
            return false;
    }
    if(pJson.isMember("volume"))
    {
        if(!validJsonOfField(4, "volume", pJson["volume"], err, false))
            return false;
    }
    if(pJson.isMember("length"))
    {
        if(!validJsonOfField(5, "length", pJson["length"], err, false))
            return false;
    }
    if(pJson.isMember("train_num_url"))
    {
        if(!validJsonOfField(6, "train_num_url", pJson["train_num_url"], err, false))
            return false;
    }
    if(pJson.isMember("dead_weight_url"))
    {
        if(!validJsonOfField(7, "dead_weight_url", pJson["dead_weight_url"], err, false))
            return false;
    }
    if(pJson.isMember("rough_weight_url"))
    {
        if(!validJsonOfField(8, "rough_weight_url", pJson["rough_weight_url"], err, false))
            return false;
    }
    if(pJson.isMember("volume_url"))
    {
        if(!validJsonOfField(9, "volume_url", pJson["volume_url"], err, false))
            return false;
    }
    if(pJson.isMember("length_url"))
    {
        if(!validJsonOfField(10, "length_url", pJson["length_url"], err, false))
            return false;
    }
    if(pJson.isMember("picture_id"))
    {
        if(!validJsonOfField(11, "picture_id", pJson["picture_id"], err, false))
            return false;
    }
    return true;
}
bool Detail::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                              const std::vector<std::string> &pMasqueradingVector,
                                              std::string &err)
{
    if(pMasqueradingVector.size() != 12)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Detail::validJsonOfField(size_t index,
                              const std::string &fieldName,
                              const Json::Value &pJson,
                              std::string &err,
                              bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isNumeric())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isUInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
void Detail::getPicture(const DbClientPtr &clientPtr,
                        const std::function<void(Picture)> &rcb,
                        const ExceptionCallback &ecb) const
{
    const static std::string sql = "select * from picture where id = ?";
    *clientPtr << sql
               << *pictureId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Picture(r[0]));
                    }
               }
               >> ecb;
}
