/**
 *
 *  History.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace sqlite3
{
class Train;

class History
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _time;
        static const std::string _train_mode;
        static const std::string _train_num;
        static const std::string _dead_weight;
        static const std::string _rough_weight;
        static const std::string _volume;
        static const std::string _length;
        static const std::string _pic_url;
        static const std::string _train_id;
    };

    const static int primaryKeyNumber;
    const static std::string tableName;
    const static bool hasPrimaryKey;
    const static std::string primaryKeyName;
    using PrimaryKeyType = uint64_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit History(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit History(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    History(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    History() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const uint64_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const uint64_t &pId) noexcept;

    /**  For column time  */
    ///Get the value of the column time, returns the default value if the column is null
    const std::string &getValueOfTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTime() const noexcept;
    ///Set the value of the column time
    void setTime(const std::string &pTime) noexcept;
    void setTime(std::string &&pTime) noexcept;
    void setTimeToNull() noexcept;

    /**  For column train_mode  */
    ///Get the value of the column train_mode, returns the default value if the column is null
    const std::string &getValueOfTrainMode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTrainMode() const noexcept;
    ///Set the value of the column train_mode
    void setTrainMode(const std::string &pTrainMode) noexcept;
    void setTrainMode(std::string &&pTrainMode) noexcept;
    void setTrainModeToNull() noexcept;

    /**  For column train_num  */
    ///Get the value of the column train_num, returns the default value if the column is null
    const std::string &getValueOfTrainNum() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTrainNum() const noexcept;
    ///Set the value of the column train_num
    void setTrainNum(const std::string &pTrainNum) noexcept;
    void setTrainNum(std::string &&pTrainNum) noexcept;
    void setTrainNumToNull() noexcept;

    /**  For column dead_weight  */
    ///Get the value of the column dead_weight, returns the default value if the column is null
    const std::string &getValueOfDeadWeight() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getDeadWeight() const noexcept;
    ///Set the value of the column dead_weight
    void setDeadWeight(const std::string &pDeadWeight) noexcept;
    void setDeadWeight(std::string &&pDeadWeight) noexcept;
    void setDeadWeightToNull() noexcept;

    /**  For column rough_weight  */
    ///Get the value of the column rough_weight, returns the default value if the column is null
    const std::string &getValueOfRoughWeight() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRoughWeight() const noexcept;
    ///Set the value of the column rough_weight
    void setRoughWeight(const std::string &pRoughWeight) noexcept;
    void setRoughWeight(std::string &&pRoughWeight) noexcept;
    void setRoughWeightToNull() noexcept;

    /**  For column volume  */
    ///Get the value of the column volume, returns the default value if the column is null
    const std::string &getValueOfVolume() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getVolume() const noexcept;
    ///Set the value of the column volume
    void setVolume(const std::string &pVolume) noexcept;
    void setVolume(std::string &&pVolume) noexcept;
    void setVolumeToNull() noexcept;

    /**  For column length  */
    ///Get the value of the column length, returns the default value if the column is null
    const std::string &getValueOfLength() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getLength() const noexcept;
    ///Set the value of the column length
    void setLength(const std::string &pLength) noexcept;
    void setLength(std::string &&pLength) noexcept;
    void setLengthToNull() noexcept;

    /**  For column pic_url  */
    ///Get the value of the column pic_url, returns the default value if the column is null
    const std::string &getValueOfPicUrl() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getPicUrl() const noexcept;
    ///Set the value of the column pic_url
    void setPicUrl(const std::string &pPicUrl) noexcept;
    void setPicUrl(std::string &&pPicUrl) noexcept;
    void setPicUrlToNull() noexcept;

    /**  For column train_id  */
    ///Get the value of the column train_id, returns the default value if the column is null
    const uint64_t &getValueOfTrainId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<uint64_t> &getTrainId() const noexcept;
    ///Set the value of the column train_id
    void setTrainId(const uint64_t &pTrainId) noexcept;


    static size_t getColumnNumber() noexcept {  return 10;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    void getTrain(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(Train)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<History>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<History>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<uint64_t> id_;
    std::shared_ptr<std::string> time_;
    std::shared_ptr<std::string> trainMode_;
    std::shared_ptr<std::string> trainNum_;
    std::shared_ptr<std::string> deadWeight_;
    std::shared_ptr<std::string> roughWeight_;
    std::shared_ptr<std::string> volume_;
    std::shared_ptr<std::string> length_;
    std::shared_ptr<std::string> picUrl_;
    std::shared_ptr<uint64_t> trainId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[10]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = ?";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = ?";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[1])
        {
            sql += "time,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "train_mode,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "train_num,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "dead_weight,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "rough_weight,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "volume,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "length,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "pic_url,";
            ++parametersCount;
        }
        if(dirtyFlag_[9])
        {
            sql += "train_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        if(dirtyFlag_[1])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[2])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[3])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[4])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[5])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[6])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[7])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[8])
        {
            sql.append("?,");

        }
        if(dirtyFlag_[9])
        {
            sql.append("?,");

        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        sql.append(1, ')');
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace sqlite3
} // namespace drogon_model
